README.md
package.json
src/ReactMinimalPieChartPath.js

I suggest removing the ```svg-partial-circle``` dependency. The only thing it does is exposing one function copied from stackoverflow, and it exposes the function as an arrow function without being transpiled (or uglified/minified). So when I tried to use you package in a [create-react-app](https://github.com/facebookincubator/create-react-app) project, the build broke because of it.
And its fancier with no dependencies than one dependency :v:

Remove svg-partial-circle as a dependency

---

src/ReactMinimalPieChart.js

SVGs are images, which are display: inline. The means there is a couple
pixels of added padding on the bottom. This causes issues when try to
align the pie chart with other components.

ReactMinimalPieChart: make SVG display: block

---

package.json

I used the current version with React 16 and everything works, except for that `yarn check` fails with an error because of an unsatisfied peer dependency.

package.json: Allow React 16 as a peer dependency

---

CHANGELOG.md
src/ReactMinimalPieChart.js
src/__tests__/ReactMinimalPieChart.js

Bug
#8 
Cancel both `setTimeout` and `requestAnimationFrame` async callbacks on unmount if still pending

Prevent initial animation when component is unmounted

---

README.md
src/__tests__/ReactMinimalPieChart.js
stories/index.js

docs/tests update
Current docs and tests using this `data` as basic example:
```js
[
{ value: 10, key: 1, color: '#E38627' },
{ value: 15, key: 2, color: '#C13C37' },
{ value: 20, key: 3, color: '#6A2135' },
]
```
It turns out that **`key` property should not be not necessary in 99% of use cases**.
- Remove test properties from both docs and tests data objects.
- Add a note to docs about what is `key` property for and to use it
No

Remove key property for basic use cases

---

CHANGELOG.md
README.md
package.json
src/ReactMinimalPieChart.js
src/__tests__/ReactMinimalPieChart.js
stories/index.js

Feature
SVG paths support [gradient stroke color](https://www.w3schools.com/graphics/svg_grad_linear.asp) by appending a `<defs>` element into `<svg>` element.
Injecting custom elements into rendered `<svg>` element is currently impossible.
See issue #22.
Add an `inject` (would `injectSvg` a better name?) property to render any custom element as `<svg>`children.
No

Support injectSvg property

---

CHANGELOG.md
src/ReactMinimalPieChart.js
src/__tests__/ReactMinimalPieChart.js
src/__tests__/ReactMinimalPieChartPath.js
stories/index.js

Fix
Missing `<path>` > `<title>` element when `data.title` is provided
Provide `title` prop to `<ReactMinimalPieChartPath>` component
No

Fix missing data.title output

---

rollup.config.js
src/ReactMinimalPieChart.js

Refactor
`<ReactMinimalPieChart>` extends React.PureComponent class
`<ReactMinimalPieChart>`extends React.Component class. 
Extending React.PureComponent was premature optimisation.
Yes

Let <ReactMinimalPieChart> extend React.Component class

---

README.md
src/ReactMinimalPieChart.js
src/__tests__/ReactMinimalPieChart.js

Bug fix
`paddingAngle` implementation doesn't respect proportions of rendered slices.
Re-evaluate rendered slices' degrees based on padding value
Add extra `startOffset` property to extended data set, in order to get rid of the pointers necessary to sequentially render the slices.
Yes

Improve paddingAngle implementation to respect slices' proportions

---

.travis.yml
package-lock.json
package.json

Dev dependencies update
- Update `rollup` to allow renovate to update `rollup` plugins.
- Run CI against last LTS Node only
No

Update dependency rollup to v1.16.x

---

jest/__snapshots__/bundles-snapshot.test.js.snap
package.json
src/ReactMinimalPieChartLabel.js

Bug fix
`alignment-baseline` [doesn't work as expected](https://stackoverflow.com/questions/19212498/firefox-support-for-alignment-baseline-property) on Firefox.
Add `dominant-baseline` property in addition to the existing `alignment-baseline`.
Yes, if the user relies on `labelStyle` prop to override default  `alignment-baseline`.
#67

Vertical align label with dominant-baseline

---

jest/__snapshots__/bundles-snapshot.test.js.snap
src/ReactMinimalPieChartPath.js
src/__tests__/ReactMinimalPieChartPath.js

Bug fix
`reveal` prop reveals path in the opposite direction of `lengthAngle` prop
Make `reveal` go same direction as `lengthAngle`.
Yes. `reveal` property will reveal the chart path using the opposite direction then before. Same goes for animations direction.
#53

Make reveal prop work same direction as lengthAngle

---

jest/__snapshots__/bundles-snapshot.test.js.snap
src/ReactMinimalPieChartPath.js
src/__tests__/ReactMinimalPieChartPath.js

Bug fix
`reveal` doesn't reverse animation direction when `lengthAngle` is negative
`reveal` animation direction follows `lengthAngle`.
Yes, but previous behaviour was a bug.

Fix reveal with negative lengthAngle

---

jest/__snapshots__/bundles-snapshot.test.js.snap
src/Chart.js

Fix error on console when totalValue is 0, and sum of all Values is 0.
This does not have any visual impact.
No error in the console.
Visually is the same result.
Nope
- [-] Docs have been added / updated

Fix error on console when totalValue equals zero

---

.all-contributorsrc
CHANGELOG.md
README.md
jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart.js
src/__tests__/Chart.test.js
src/types/__tests__/test.ts
src/types/index.d.ts
src/utils.js
stories/index.js

Bug fix
See #106 
Add property to customise SVG `viewBox` attribute width/height.
YES. `ratio` property is removed and replaced with `viewBox`.
In order to change the chart ratio provide an explicit `viewBoxSize` value (it defaults at `[100, 100]`).
```diff
- ratio: 2
+ viewBoxSize: [100, 50]
```

Introduce custom viewBoxSize prop

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart.js
src/__tests__/Chart.test.js
src/__tests__/testUtils.js

Bug fix
`cy` evaluated from `viewBoxSize` width instead of height. https://github.com/toomuchdesign/react-minimal-pie-chart/issues/106#issuecomment-562162207
evaluate `cy` from `viewBoxSize` height. 
Yes, but the previous behaviour was wrong.

Fix: evaluate SVG cy value based on viewBoxSize height

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart/renderSegments.tsx
src/Path.tsx

Internal refactoring
`Path` components types are defined loosely by accepting any kind of optional props.
Make each `Path` prop explicitly typed,
No, `Path` is not publicly exposed.

Make Path component types stricter

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart/index.tsx
src/Chart/renderSegments.tsx
src/__tests__/Chart.test.tsx
src/__tests__/Path.test.tsx

Bug fix
v7.0.0 [introduced a regression bug ](https://github.com/toomuchdesign/react-minimal-pie-chart/blame/f8cd27b1de5ff3b9b253a9884d890a6cf1460e82/src/Chart/index.tsx#L98)consisting of `stroke-dasharray` and `stroke-dashoffset` attributes being evaluated and appended even when there is no animation.
This PR fixes the regression bug and add tests to cover this specific case.
It also gets rid of one of the most [cumbersome lines of code](https://github.com/toomuchdesign/react-minimal-pie-chart/blob/f8cd27b1de5ff3b9b253a9884d890a6cf1460e82/src/Chart/renderSegments.tsx#L41) of this library.
Yes, but it reverts the library to its expected behaviour.

Prevent animation attributes from being uselessy evaluated

---

CHANGELOG.md
jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart/Chart.tsx
src/Chart/renderSegments.tsx
src/Path.tsx
src/__tests__/Chart.test.tsx
src/__tests__/testUtils/render.js
src/utils.ts

Bug fix
53c2e69cb500d7e9af287cffd93b817a21b82a42 Introduced a bug concerning `reveal` prop getting stuck after initial animation
This PR provide a bugfix and tests
No

Fix reveal prop stuck after initial animation

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart/renderLabels.tsx
src/__tests__/Path.test.tsx

Bug fix
#155 
Rephrased the line which caused the bug. Tests did catch the bug because of a test implementation detail which set `labelPosition` to 0. 🙀
No

Fix wrong label position when segmentsShift enabled (#155)

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart/Chart.tsx
src/Chart/renderSegments.tsx
src/__tests__/types.tsx
src/commonTypes.ts

Types Bug fix
`onBlur`, `onFocus` and `onKeyDown` types expect wrong `MouseEvent` event type.
Assign correct event type and enable type checking on the lines which had it disabled.
No

Event handler types fix

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/__tests__/Chart.test.tsx
src/utils.ts

Bug fix, still to be implemented.
#133
Expect `stroke-dashoffset` attribute to always exactly equal 0 after animation. This PR redefines `extractPercentage` implementation to avoid rounding errors when percentage is 100 or 0.
No

Fix stroke-dashoffset attribute zero rounding error

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart/Chart.tsx
src/Chart/index.tsx
src/Chart/renderSegments.tsx
src/Label.tsx
src/Path.tsx

Removed displayName property to reduce bundle size. Since strings can't be minified, reducing them affects bundlesize.
For example, having "Path" +  "displayName" + "ReactMinimalPieChartPath" takes 39 characters (or bytes) while ReactMinimalPieChartPath takes 24). Also, I guess you care for how your component appears in the react tree in debugger or profiler, so naming the function itself as the desired component name should do what you want as named functions anyway have a name in React tree:
...
Current bundlesize is `1.87 KB with all dependencies, minified and gzipped`
...
New bundlesize is ` 1.83 KB with all dependencies, minified and gzipped`. This is a 2% win. 🤷‍♂️
...
I hope not.
...

feat: rely on function names for displayName (2% bundle size reduction)

---

README.md
jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart/Chart.tsx
src/Chart/extendData.ts
src/Chart/index.tsx
src/Chart/renderLabels.tsx
src/Chart/renderSegments.tsx
src/Label.tsx
src/__tests__/Chart.test.tsx
src/__tests__/Label.test.tsx
src/__tests__/types.tsx
src/commonTypes.ts
src/index.ts
src/utils.ts
stories/FullOption.tsx
stories/InteractionStory.tsx
stories/InteractionTabStory.tsx
stories/Tooltip.tsx
stories/index.tsx

Feature
`data` doesn't consider any custom prop
Type `data` props with generics and expose `PieChartProps` type.
Remove dependency over React's deprecated `defaultProps`.
No

feat: type data with generics

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart/Chart.tsx
src/__tests__/Chart.test.tsx

Refactor
Initial animation triggered on `useEffect` + `setTimeout` + `requestAnimationFrame`
Triggering a state update with `useEffect` should be enough to guarantee that the component is initially painted with hidden segments and then animation is triggered.
No, it shouldn't. Should we run into regression bug we can safely revert this commit.

refactor: trigger initial animation with useEffect only

---

README.md

docs
Commit cdf31755d708694b31833c27d438803904817f4b moved the location of the `Tooltip.tsx` file without updating all of the sources.
PR fixes the sources with the correct changes
No

fix: update demo tooltip source reference
