.eslintignore
.gitignore
.prettierignore
README.md
package-lock.json
package.json

Dev tool update
**Storybook** needs manual deployment on **andreacarraro.it**
Automate process with `storybook-to-ghpages`
No
Consider moving storybook deployment to CI.

Autodeploy storybook to github pages

---

README.md

Add NPM and size badges

---

package.json

Add `sideEffects` flag to package.json
No

Add sideEffect flag

---

src/ReactMinimalPieChart.js
src/ReactMinimalPieChartPath.js

Refactor
Several functions declared as arrow function for no real reason.
Replace anonymous arrow functions with named ones
No

Replace anonymous arrow functions with named ones

---

.travis.yml
package-lock.json
package.json

Tooling feature
Ensure that bundle size is < 3kb on `preversion` and `prepublish`.
No

Add 3kb size-limit prepublish check

---

README.md
package-lock.json
package.json
src/types/__tests__/test.ts
src/types/__tests__/tsconfig.json
src/types/index.d.ts

Feature
TS definitions support
Yes for TS users

Add TS types definitions

---

.all-contributorsrc
CHANGELOG.md
README.md
package-lock.json
package.json

Update v4.0.0 docs

---

src/ReactMinimalPieChart.js

feature
...
segmentsStyle allows you to have a global style for all segments
...
props.data[i].style allows users to overwrite segmentsStyle for individual segments
...
No
...

Allow styling individual segments via props.data[i].style

---

package-lock.json
package.json

Deps update:
- coveralls
- husky
- lint-staged
- prettier

Update some dev dependencies

---

jest/__snapshots__/bundles-snapshot.test.js.snap
jest/bundles-snapshot.test.js
package.json

Test feature
When updating bundling dependencies there's no way to spot possible changes introduced by the new packages versions (event though bundles are also unit tested).
Add a snapshot test targeting one of the bundles (dist).
No

Update bundle tests

---

CHANGELOG.md

Update docs v5.0.0

---

CHANGELOG.md
README.md

Update docs for v5.0.1

---

README.md

Add Edge support notice

---

jest/__snapshots__/bundles-snapshot.test.js.snap
src/Chart.js
src/__tests__/Chart.js

Bug fix
See #80.
No
Thanks @Osuka42g!

Prevent "NaN" from being rendered as SVG path attribute value

---

.travis.yml
jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
package.json
src/Chart.js
src/utils.js

Minor improvements
Fix a couple of details in code and replace `prepublish` script with `prepare`.
No

Mini update

---

CHANGELOG.md
README.md

docs update for v7
...
...
...

Docs update for v7

---

.all-contributorsrc
CHANGELOG.md
README.md

v7.3.1 docs update

---

CHANGELOG.md
README.md

V8.0.0 docs update

---

.storybook/addons.js
.storybook/config.js
.storybook/main.js
package-lock.json
package.json

Remove storybook's source code

---

README.md
package-lock.json
package.json
stories/Tooltip.tsx
stories/index.tsx

Add tooltip integration demo

---

CHANGELOG.md

v8.0.1 docs update
...
...
...

v8.0.1 docs update

---

package.json

Allow React 18 peer dep

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart/Chart.tsx
src/Chart/renderLabels.tsx
src/Chart/renderSegments.tsx
src/Label.tsx
src/commonTypes.ts

Refactor
- Extract initial animation effect as useEffectAfterFirstPaint hook
- Make event handler helper types stricter
- Cleanup Label component and fix key assignment
No

refactor: minor details before release

---

CHANGELOG.md

docs: update docs

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap
src/Chart/Chart.tsx
src/Chart/renderSegments.tsx
src/utils.ts

Refactor
Improve some types
No

refactor: improve types

---

.prettierignore
.prettierrc
@types/svg-partial-circle/index.d.ts
package-lock.json
package.json
src/Chart/Chart.tsx
src/Chart/renderSegments.tsx
src/Label.tsx
src/__tests__/Path.test.tsx
src/commonTypes.ts

chore: remove lint-staged

---

.github/workflows/deploy-storybook.yml

fix: storybook deployment

---

.github/workflows/dependabot-auto-merge.yml

chore: setup dependabot auto merge action

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/dependabot-auto-merge.yml

chore: update gh actions

---

jest/__tests__/__snapshots__/bundles-snapshot.test.js.snap

chore: fix ci

---

README.md
package-lock.json
package.json

docs: minor fixes

---

CHANGELOG.md
package-lock.json
package.json
rollup.config.js

fix: move @types/svg-path-parser to dev dependencies

---

package-lock.json
package.json

Feature
Open support to v19
No

feat: support react v19
